# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# PER-DEPLOY.

[[redirects]]
  from = "/"
  to = "/it/"
#  conditions = {Language = ["it"]}

[[redirects]]
  from = "/"
  to = "/it/"

[[redirects]]
  from = "/azienda*"
  to = "/it/"
  conditions = {Language = ["it"]}

[[redirects]]
  from = "/categorie1*"
  to = "/it/"
  conditions = {Language = ["it"]}

[[redirects]]
  from = "/categorie2*"
  to = "/it/"
  conditions = {Language = ["it"]}

[[redirects]]
  from = "/contattaci*"
  to = "/it/"
  conditions = {Language = ["it"]}

[[redirects]]
  from = "/home1*"
  to = "/it/"
  conditions = {Language = ["it"]}

[[redirects]]
  from = "/info*"
  to = "/it/"
  conditions = {Language = ["it"]}

[[redirects]]
  from = "/prodotto*"
  to = "/it/"
  conditions = {Language = ["it"]}

[[redirects]]
  from = "/professionale*"
  to = "/it/"
  conditions = {Language = ["it"]}

[[redirects]]
  from = "/rivenditori*"
  to = "/it/"
  conditions = {Language = ["it"]}